-- SAGA outgoing content APIs: Vercel/Neon-only, read-only bearer exports.
--
-- This table deliberately keeps an opaque key prefix and a one-way SHA-256
-- hash only. The full bearer secret is generated by the server and is never
-- persisted, returned by a list route, or attached to a destination URL.

begin;

create or replace function saga_outgoing_api_content_types_are_valid(value text[])
returns boolean
language sql
immutable
as $$
  select value is not null
    and cardinality(value) between 1 and 3
    and array_position(value, null) is null
    and value <@ array['social_post', 'newsletter', 'article']::text[]
    and cardinality(value) = cardinality(array(select distinct entry from unnest(value) as entry));
$$;

create table if not exists saga_outgoing_content_apis (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references app_workspaces(id) on delete cascade,
  created_by_user_id uuid not null,
  name text not null check (char_length(trim(name)) between 2 and 120),
  content_type_scope text not null default 'all'
    check (content_type_scope in ('all', 'selected')),
  content_types text[] not null default array['social_post', 'newsletter', 'article']::text[]
    check (saga_outgoing_api_content_types_are_valid(content_types)),
  visibility text not null default 'published_only'
    check (visibility in ('published_only', 'publication_ready')),
  -- A prefix is not a credential. It exists only to locate a candidate hash
  -- without scanning every tenant's API rows.
  key_prefix text not null unique
    check (key_prefix ~ '^saga_out_live_[A-Za-z0-9_-]{12}$'),
  secret_hash text not null unique
    check (secret_hash ~ '^[a-f0-9]{64}$'),
  expires_at timestamptz,
  last_used_at timestamptz,
  revoked_at timestamptz,
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or expires_at > created_at),
  check (
    (content_type_scope = 'all' and content_types = array['social_post', 'newsletter', 'article']::text[])
    or (content_type_scope = 'selected' and cardinality(content_types) between 1 and 3)
  ),
  unique (workspace_id, id),
  foreign key (workspace_id, created_by_user_id)
    references app_workspace_memberships(workspace_id, user_id)
    on delete restrict
);

create index if not exists saga_outgoing_content_apis_workspace_created_idx
  on saga_outgoing_content_apis(workspace_id, created_at desc);
create index if not exists saga_outgoing_content_apis_active_prefix_idx
  on saga_outgoing_content_apis(key_prefix)
  where revoked_at is null;

drop trigger if exists saga_outgoing_content_apis_set_updated_at on saga_outgoing_content_apis;
create trigger saga_outgoing_content_apis_set_updated_at
before update on saga_outgoing_content_apis
for each row execute function app_set_updated_at();

commit;
