import "server-only";

import { randomUUID } from "node:crypto";
import { del, head, put } from "@vercel/blob";
import { executionAbortSignal } from "@/lib/server/execution-deadline";

const STUDIO_BLOB_PREFIX = "studio/workspaces";
const MAX_IMAGE_BYTES = 20 * 1024 * 1024;
const MAX_FILE_NAME_LENGTH = 180;
const ONE_YEAR_IN_SECONDS = 60 * 60 * 24 * 365;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

const supportedImageTypes = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
} as const;

export type StudioBlobContentType = keyof typeof supportedImageTypes;

declare const trustedStudioBlobPath: unique symbol;

/**
 * A pathname that has been generated by this module or validated against a
 * server-resolved workspace and draft. It intentionally cannot be created
 * from a public URL.
 */
export type TrustedStudioBlobPath = string & {
  readonly [trustedStudioBlobPath]: true;
};

export type StudioBlobScope = {
  workspaceId: string;
  draftId: string;
};

export type UploadedStudioBlob = {
  /** Private Blob URL for server-side storage/metadata only. */
  url: string;
  pathname: TrustedStudioBlobPath;
  contentType: StudioBlobContentType;
  size: number;
};

export class VercelBlobMediaError extends Error {
  constructor(message: string, readonly status: number) {
    super(message);
    this.name = "VercelBlobMediaError";
  }
}

export class MissingVercelBlobConfigurationError extends VercelBlobMediaError {
  constructor() {
    super("Vercel Blob är inte konfigurerat. Lägg till BLOB_READ_WRITE_TOKEN i Vercel.", 503);
    this.name = "MissingVercelBlobConfigurationError";
  }
}

/** Returns names only; the token itself is never exposed to callers. */
export function missingVercelBlobConfiguration(): string[] {
  return process.env.BLOB_READ_WRITE_TOKEN?.trim() ? [] : ["BLOB_READ_WRITE_TOKEN"];
}

export function isVercelBlobConfigured(): boolean {
  return missingVercelBlobConfiguration().length === 0;
}

/**
 * Uploads a Studio image with a server-generated, workspace-scoped pathname.
 * This is intentionally a server upload: no browser token or arbitrary URL is
 * ever accepted by the helper.
 */
export async function uploadStudioBlob(input: {
  scope: StudioBlobScope;
  bytes: Uint8Array;
  fileName: string;
  contentType: string;
  /**
   * A trusted durable receipt id. When present, the Blob pathname is stable
   * across a worker retry, so a lost response cannot create a second private
   * object for the same receipt. This is intentionally server-only: callers
   * still cannot choose a workspace, draft, or arbitrary pathname.
   */
  stableObjectId?: string;
}): Promise<UploadedStudioBlob> {
  const token = getVercelBlobToken();
  const scope = normalizeScope(input.scope);
  const contentType = validateContentType(input.contentType);
  const size = validateBytes(input.bytes);
  const pathname = createStudioBlobPath(scope, input.fileName, contentType, input.stableObjectId);

  let uploaded: Awaited<ReturnType<typeof put>>;
  try {
    uploaded = await put(pathname, Buffer.from(input.bytes), {
      access: "private",
      addRandomSuffix: false,
      allowOverwrite: false,
      contentType,
      cacheControlMaxAge: ONE_YEAR_IN_SECONDS,
      token,
      ...blobCancellation(),
    });
  } catch {
    // Cancellation must not start a recovery HEAD or another write.
    executionAbortSignal();
    // A durable media worker may be resumed after its Blob PUT completed but
    // before it could commit Neon metadata. Reuse exactly the same private
    // object for its stable receipt instead of creating a sibling image.
    if (input.stableObjectId) {
      try {
        const existing = await head(pathname, { token, ...blobCancellation() });
        if (existing.pathname !== pathname || existing.contentType !== contentType || existing.size <= 0 || existing.size > MAX_IMAGE_BYTES) {
          throw new VercelBlobMediaError("Vercel Blob returnerade ett oväntat tidigare bildobjekt.", 502);
        }
        return {
          url: assertPrivateBlobUrl(existing.url, pathname),
          pathname,
          contentType,
          size: existing.size,
        };
      } catch (reuseError) {
        executionAbortSignal();
        if (reuseError instanceof VercelBlobMediaError) throw reuseError;
        throw new VercelBlobMediaError("Kunde inte läsa det privata bildobjektet för den återupptagna körningen.", 502);
      }
    }
    throw new VercelBlobMediaError("Kunde inte lagra filen i Vercel Blob.", 502);
  }

  try {
    if (uploaded.pathname !== pathname) {
      throw new VercelBlobMediaError("Vercel Blob returnerade en oväntad filsökväg.", 502);
    }

    return {
      url: assertPrivateBlobUrl(uploaded.url, pathname),
      pathname,
      contentType,
      size,
    };
  } catch (error) {
    // We only ever clean up the pathname generated above, never a URL or a
    // pathname received from a client.
    await del(pathname, { token, ...blobCancellation() }).catch(() => undefined);
    throw error;
  }
}

/**
 * Resolves metadata for one already-server-generated private Blob object.
 * It accepts an exact workspace/draft scope plus a trusted pathname, never a
 * browser URL, so a durable worker can attach the precise object after a
 * lease retry without making that URL browser-visible.
 */
export async function getPrivateStudioBlobMetadata(input: {
  scope: StudioBlobScope;
  pathname: TrustedStudioBlobPath;
}): Promise<UploadedStudioBlob> {
  const token = getVercelBlobToken();
  const scope = normalizeScope(input.scope);
  const pathname = assertTrustedStudioBlobPath(scope, input.pathname);
  try {
    const existing = await head(pathname, { token, ...blobCancellation() });
    const contentType = validateContentType(existing.contentType);
    if (existing.pathname !== pathname || existing.size <= 0 || existing.size > MAX_IMAGE_BYTES) {
      throw new VercelBlobMediaError("Vercel Blob returnerade ett oväntat privat bildobjekt.", 502);
    }
    return {
      url: assertPrivateBlobUrl(existing.url, pathname),
      pathname,
      contentType,
      size: existing.size,
    };
  } catch (error) {
    executionAbortSignal();
    if (error instanceof VercelBlobMediaError) throw error;
    throw new VercelBlobMediaError("Kunde inte läsa den privata bildens metadata från Vercel Blob.", 502);
  }
}

/**
 * Validates a database-resolved Blob pathname before deletion. Routes should
 * first look up the media row with workspace + draft ownership, then pass its
 * stored pathname here. Do not pass request body values directly.
 */
export function assertTrustedStudioBlobPath(scope: StudioBlobScope, pathname: string): TrustedStudioBlobPath {
  const normalizedScope = normalizeScope(scope);
  if (typeof pathname !== "string" || pathname.length > 512 || pathname.includes("?") || pathname.includes("#")) {
    throw new VercelBlobMediaError("Bildens filsökväg är ogiltig.", 400);
  }

  const expectedPrefix = `${STUDIO_BLOB_PREFIX}/${normalizedScope.workspaceId}/drafts/${normalizedScope.draftId}/`;
  if (!pathname.startsWith(expectedPrefix) || !isSafeStudioBlobLeaf(pathname.slice(expectedPrefix.length))) {
    throw new VercelBlobMediaError("Bildens filsökväg ligger utanför det valda utkastet.", 400);
  }

  return pathname as TrustedStudioBlobPath;
}

/**
 * Deletes only a validated, workspace-and-draft-scoped pathname. The helper
 * deliberately accepts no Blob URL; callers must retain and resolve the path
 * from their own authorized media record first.
 */
export async function deleteStudioBlob(input: {
  scope: StudioBlobScope;
  pathname: TrustedStudioBlobPath;
}): Promise<void> {
  const token = getVercelBlobToken();
  const pathname = assertTrustedStudioBlobPath(input.scope, input.pathname);

  try {
    await del(pathname, { token, ...blobCancellation() });
  } catch {
    executionAbortSignal();
    throw new VercelBlobMediaError("Kunde inte ta bort filen från Vercel Blob.", 502);
  }
}

/** Blob consumes abortSignal, whereas the Gateway/Neon adapters use signal. */
function blobCancellation(): { abortSignal?: AbortSignal } {
  const signal = executionAbortSignal();
  return signal ? { abortSignal: signal } : {};
}

/** Creates an opaque server-generated pathname; it is never sourced from a request pathname. */
export function createStudioBlobPath(
  scope: StudioBlobScope,
  fileName: string,
  contentType: StudioBlobContentType,
  stableObjectId?: string,
): TrustedStudioBlobPath {
  const normalizedScope = normalizeScope(scope);
  const safeName = safeFileStem(fileName);
  const extension = supportedImageTypes[contentType];
  const objectId = stableObjectId ? normalizeStableObjectId(stableObjectId) : randomUUID();
  const pathname = `${STUDIO_BLOB_PREFIX}/${normalizedScope.workspaceId}/drafts/${normalizedScope.draftId}/${objectId}-${safeName}.${extension}`;
  return assertTrustedStudioBlobPath(normalizedScope, pathname);
}

function getVercelBlobToken(): string {
  const token = process.env.BLOB_READ_WRITE_TOKEN?.trim();
  if (!token) throw new MissingVercelBlobConfigurationError();
  return token;
}

function normalizeScope(scope: StudioBlobScope): StudioBlobScope {
  if (!scope || typeof scope.workspaceId !== "string" || typeof scope.draftId !== "string") {
    throw new VercelBlobMediaError("Arbetsyta och utkast måste anges för bilden.", 400);
  }

  const workspaceId = scope.workspaceId.trim().toLowerCase();
  const draftId = scope.draftId.trim().toLowerCase();
  if (!uuidPattern.test(workspaceId) || !uuidPattern.test(draftId)) {
    throw new VercelBlobMediaError("Arbetsyta och utkast måste vara giltiga id:n.", 400);
  }

  return { workspaceId, draftId };
}

/** The stable object key is accepted only as a UUID produced by a server receipt. */
function normalizeStableObjectId(value: string): string {
  const objectId = value.trim().toLowerCase();
  if (!uuidPattern.test(objectId)) {
    throw new VercelBlobMediaError("Bildens beständiga körnings-id är ogiltigt.", 400);
  }
  return objectId;
}

function validateContentType(value: string): StudioBlobContentType {
  const contentType = typeof value === "string" ? value.trim().toLowerCase() : "";
  if (!(contentType in supportedImageTypes)) {
    throw new VercelBlobMediaError("Välj en JPG-, PNG- eller WebP-bild.", 400);
  }
  return contentType as StudioBlobContentType;
}

function validateBytes(value: Uint8Array): number {
  if (!(value instanceof Uint8Array) || value.byteLength <= 0 || value.byteLength > MAX_IMAGE_BYTES) {
    throw new VercelBlobMediaError("Bilden måste vara större än 0 och högst 20 MB.", 400);
  }
  return value.byteLength;
}

function safeFileStem(value: string): string {
  if (typeof value !== "string") throw new VercelBlobMediaError("Bildens filnamn saknas.", 400);

  const fileName = value.trim();
  if (!fileName || fileName.length > MAX_FILE_NAME_LENGTH || /[\\/\u0000-\u001f]/.test(fileName) || fileName === "." || fileName === "..") {
    throw new VercelBlobMediaError("Bildens filnamn är ogiltigt.", 400);
  }

  const stem = fileName.replace(/\.[^.]+$/, "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "");
  const safeName = stem.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 96);
  return safeName || "image";
}

function isSafeStudioBlobLeaf(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}-[a-z0-9][a-z0-9-]{0,95}\.(jpg|png|webp)$/i.test(value);
}

function assertPrivateBlobUrl(value: string, expectedPathname: TrustedStudioBlobPath): string {
  try {
    const url = new URL(value);
    if (
      url.protocol !== "https:"
      || !url.hostname.endsWith(".blob.vercel-storage.com")
      || url.username
      || url.password
      || url.search
      || url.hash
      || url.pathname !== `/${expectedPathname}`
    ) {
      throw new Error("invalid Blob URL");
    }
    return url.toString();
  } catch {
    throw new VercelBlobMediaError("Vercel Blob returnerade en ogiltig filadress.", 502);
  }
}
